import { Option } from "./customer.constants";

export const OTHER_PROVINCE_VALUE = "Khác";

export const PROVINCE_OPTIONS: Option[] = [
  { value: "Hồ Chí Minh", label: "Hồ Chí Minh" },
  { value: "Hà Nội", label: "Hà Nội" },
  { value: OTHER_PROVINCE_VALUE, label: "Khác..." },
];

export const HCM_DISTRICTS: Option[] = [
  { value: "Quận 1", label: "Quận 1" },
  { value: "Quận 3", label: "Quận 3" },
  { value: "Quận 4", label: "Quận 4" },
  { value: "Quận 5", label: "Quận 5" },
  { value: "Quận 6", label: "Quận 6" },
  { value: "Quận 7", label: "Quận 7" },
  { value: "Quận 8", label: "Quận 8" },
  { value: "Quận 10", label: "Quận 10" },
  { value: "Quận 11", label: "Quận 11" },
  { value: "Quận 12", label: "Quận 12" },
  { value: "Quận Bình Tân", label: "Quận Bình Tân" },
  { value: "Quận Bình Thạnh", label: "Quận Bình Thạnh" },
  { value: "Quận Gò Vấp", label: "Quận Gò Vấp" },
  { value: "Quận Phú Nhuận", label: "Quận Phú Nhuận" },
  { value: "Quận Tân Bình", label: "Quận Tân Bình" },
  { value: "Quận Tân Phú", label: "Quận Tân Phú" },
  { value: "Thành phố Thủ Đức", label: "Thành phố Thủ Đức" },
  { value: "Huyện Bình Chánh", label: "Huyện Bình Chánh" },
  { value: "Huyện Cần Giờ", label: "Huyện Cần Giờ" },
  { value: "Huyện Củ Chi", label: "Huyện Củ Chi" },
  { value: "Huyện Hóc Môn", label: "Huyện Hóc Môn" },
  { value: "Huyện Nhà Bè", label: "Huyện Nhà Bè" },
];

export const HANOI_DISTRICTS: Option[] = [
  { value: "Quận Ba Đình", label: "Quận Ba Đình" },
  { value: "Quận Hoàn Kiếm", label: "Quận Hoàn Kiếm" },
  { value: "Quận Hai Bà Trưng", label: "Quận Hai Bà Trưng" },
  { value: "Quận Đống Đa", label: "Quận Đống Đa" },
  { value: "Quận Tây Hồ", label: "Quận Tây Hồ" },
  { value: "Quận Cầu Giấy", label: "Quận Cầu Giấy" },
  { value: "Quận Thanh Xuân", label: "Quận Thanh Xuân" },
  { value: "Quận Hoàng Mai", label: "Quận Hoàng Mai" },
  { value: "Quận Long Biên", label: "Quận Long Biên" },
  { value: "Quận Nam Từ Liêm", label: "Quận Nam Từ Liêm" },
  { value: "Quận Bắc Từ Liêm", label: "Quận Bắc Từ Liêm" },
  { value: "Quận Hà Đông", label: "Quận Hà Đông" },
  { value: "Thị xã Sơn Tây", label: "Thị xã Sơn Tây" },
  { value: "Huyện Ba Vì", label: "Huyện Ba Vì" },
  { value: "Huyện Chương Mỹ", label: "Huyện Chương Mỹ" },
  { value: "Huyện Đan Phượng", label: "Huyện Đan Phượng" },
  { value: "Huyện Đông Anh", label: "Huyện Đông Anh" },
  { value: "Huyện Gia Lâm", label: "Huyện Gia Lâm" },
  { value: "Huyện Hoài Đức", label: "Huyện Hoài Đức" },
  { value: "Huyện Mê Linh", label: "Huyện Mê Linh" },
  { value: "Huyện Mỹ Đức", label: "Huyện Mỹ Đức" },
  { value: "Huyện Phú Xuyên", label: "Huyện Phú Xuyên" },
  { value: "Huyện Phúc Thọ", label: "Huyện Phúc Thọ" },
  { value: "Huyện Quốc Oai", label: "Huyện Quốc Oai" },
  { value: "Huyện Sóc Sơn", label: "Huyện Sóc Sơn" },
  { value: "Huyện Thạch Thất", label: "Huyện Thạch Thất" },
  { value: "Huyện Thanh Oai", label: "Huyện Thanh Oai" },
  { value: "Huyện Thanh Trì", label: "Huyện Thanh Trì" },
  { value: "Huyện Thường Tín", label: "Huyện Thường Tín" },
  { value: "Huyện Ứng Hòa", label: "Huyện Ứng Hòa" },
];
